### ISSUE TITLE
Only collect person.id by default for person tracking

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-java#136]
Allow the ability to send person.email and person.username, but by default we should only collect person.id going forward.

@rokob This is a top priority.

**Comment by rokob** [comment]
Based on how the person is set, we don't need the configuration option here. This is because we don't do anything automatically, anywhere someone is setting the person manually they can choose what to send in exactly the same way as setting a configuration option. Moreover having both manually set person data and configuration options would be unnecessarily confusing.
