### ISSUE TITLE
rollbar-java and rollbar-api currently not updated to 1.7.0 on maven central

### ISSUE THREAD

**Issue by G00fY2** [rollbar/rollbar-java#202]
Not sure if you are aware of that and I'm just impatient. But currently after updating to rollbar-android 1.7.0 our builds fail because of missing transitive dependencies.

**Comment by basoko** [comment]
@G00fY2 Sorry, I don't know why but I think that `rollbar-api` was not finally publish in Maven. I have tried to manually published it again so hopefully you don't have that error with missing dependencies.

**Comment by james-airspace** [comment]
@G00fY2 This `rollbar-android` update halted our QA and broke all of our CCI build artifacts for the last few hours. Might be worth removing the `1.+` dependency and instead hardcode your version to `1.6.0`. That's what I did to resolve this issue.

**Comment by GreyTeardrop** [comment]
`rollbar-java` version 1.7.0 is missing `rollbar-java-1.7.0.pom` on Maven Central: https://repo.maven.apache.org/maven2/com/rollbar/rollbar-java/1.7.0/, therefore all the builds using 1.7.0 would be broken. As far as I know, there's no way to fix that within 1.7.0 release, it hase to be re-released as 1.7.0.1 or something.

**Comment by basoko** [comment]
@GreyTeardrop Don't know happen with the publication, but I was able to publish it in 1.7.0.

**Comment by G00fY2** [comment]
Can confirm that _java_ and _api_ 1.7.0 are now available but Gradle can't automatically resolve these dependencies. I guess there is something messed up with the pom files (like @GreyTeardrop said). Maybe you can investigate a little further.

**Comment by basoko** [comment]
@G00fY2 yes, seems that the pom file was finally publish but i think that release is completely broken. We are working or publishing soon another version with some fixes we also discover for jacoco in android and some improvements like trying to publish from travis.

**Comment by basoko** [comment]
We have published a new version 1.7.1 that should work as expected https://github.com/rollbar/rollbar-java/releases/tag/v1.7.1.

To try to avoid having issues with the publication, as happened with the version 1.7.0,
we have decided to upload it directly from Travis to the oss sonatype's staging repository, although this still needs some more work because multiple staging repositories are created.
On the other hand, now that we upload artifacts directly form Travis we will start publishing
SNAPSHOTS versions after every merge in master.

Also, we had added a note in the Github's releases page to discourage the use of the
1.7.0 version https://github.com/rollbar/rollbar-java/releases/tag/v1.7.0

Thanks!
