### ISSUE TITLE
Add ability to detect if exception if caught or uncaught

### ISSUE THREAD

**Issue by and-megan** [rollbar/rollbar-java#93]
and then be able to edit the payload

**Comment by doridori** [comment]
This issue was created based upon a discussion with support. 

The motivation is to be able to be able to add some meta data to the next Exception that is sent up to rollbar. 

Ideally this would be possible for both _explicitly created Exceptions_ `throw new CustomException` and _uncaught exceptions_. The former could be solved by passing in a String `reason`, but I am not sure how the latter would be possible using Rollbar?
