### ISSUE TITLE
rollbar-java not running on Huawei Honor (Android 7)

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-java#94]
[USER]:
I have an Android app that sends reports to Rollbar just fine from an emulator (Android 7) or a MotoE device (Android 6), but not from a Huawei Honor (Android 7). What could possibly be causing that?

**Comment by rokob** [comment]
I have no idea what could be causing an app on one device to act differently than on another device. There isn't a good way to debug this from my end. I need more information about what it is and isn't doing on the particular device in question. It could be a permission issue on that particular device so that nothing is getting through. It could be a mismatched sdk version.

**Comment by rivkahstandig3636** [comment]
Closing this as it is impossible to debug with no information.
